# Generated by Django 5.2.9 on 2025-12-10 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_name",
                    models.CharField(
                        blank=True,
                        help_text="사용자가 선호하는 이름이나 호칭",
                        max_length=100,
                        verbose_name="호칭/별칭",
                    ),
                ),
                (
                    "mobility_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("comfortable_walking", "걷기가 비교적 편하다"),
                            ("slow_walking", "천천히라면 걷기는 가능하다"),
                            ("indoor_only", "실내에서만 주로 움직인다"),
                            ("mostly_lying", "대부분 누워 지낸다"),
                        ],
                        help_text="평소 이동이나 움직임 정도",
                        max_length=30,
                        verbose_name="움직임/기동성",
                    ),
                ),
                (
                    "current_emotion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("anxious", "불안하다"),
                            ("lethargic", "무기력하다"),
                            ("lonely", "외롭다"),
                            ("confused", "혼란스럽다"),
                            ("sad", "슬프다"),
                            ("peaceful", "그래도 꽤 평온하다"),
                            ("hard_to_express", "말로 표현하기 어렵다"),
                        ],
                        help_text="요즘 마음 상태를 한 단어로 표현",
                        max_length=30,
                        verbose_name="현재 마음 상태",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="생년월일"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "남성"),
                            ("F", "여성"),
                            ("O", "기타"),
                            ("N", "밝히고 싶지 않음"),
                        ],
                        max_length=1,
                        verbose_name="성별",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, verbose_name="연락처"),
                ),
                (
                    "additional_checklist_data",
                    models.TextField(
                        blank=True,
                        default="{}",
                        help_text="JSON 형태로 저장되는 추가 정보",
                        verbose_name="추가 체크리스트 데이터",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필들",
                "ordering": ["-created_at"],
            },
        ),
    ]
